services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: trail-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
    user: "0" # Solves 'input/output error' and permission issues on some environments
    restart: always
